### PR TITLE
Add debug execution to the created archetypes

### PR DESCRIPTION
**Pull request by errael**
This PR is based on @jperedadnr comments at [StackOverflow](https://stackoverflow.com/questions/56197372/i-cant-debug-an-application-using-netbeans-11-with-javafx-12) modified for running debugger from IDE.

It might be better to have two debug executions. One as originally show, and call it "<id>debug</id>" and the one in this PR changing it's name to "<id>ide-debug</id>"

@neilcsmith-net has advocated, in [another issue](https://github.com/apache/netbeans/pull/1983#issuecomment-600158804), for a general solution where archetype/pom can specify common IDE actions. He suggests representatives of maven,IDEs,JavaFX and others work something out.

### CODE REVIEW

**Comment by abhinayagarwal** [comment]
I am not very keen to add the debug options by default. My preferred way to handle this would be to add a property `add-debug-configuration` to archetype with accepted values as "Y/N" (default value being "N"). If user wants the default configurations, they can input "Y" while the archetypes are created.

**Comment by errael** [comment]
> add a property ... If user wants debug configurations

OK. In my queue.

**Comment by errael** [comment]
@abhinayagarwal @jperedadnr Updated PR with required property `add-debug-configuration`. If property "Y" add two debug configurations, one for manual attach, one for IDE attach.

**Comment by errael** [comment]
While exploring the use of jlink, I noticed <javafx.mainClass> property. Is there any reason the archetypes do not set or use this?

Would the addition of this property, and it's use, be a welcome update to this PR?

**Comment by abhinayagarwal** [comment]
I merged and pushed the branch with latest changes to fix the conflicts.

**Review by johanvos — APPROVED** [review]
Looks very useful.

**Review by abhinayagarwal — APPROVED** [review]

**Pull request merged**
